sudo: required
services:
    - docker

before_install:
    - docker build -t enriquemomice/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run enriquemomice/react-test npm test -- --coverage

after_success:
    - docker build -t enriquemomice/multi-client ./client
    - docker build -t enriquemomice/multi-nginx ./nginx
    - docker build -t enriquemomice/multi-server ./server
    - docker build -t enriquemomice/multi-worker ./worker
    #Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take all our images and push them to docker hub
    - docker push enriquemomice/multi-client
    - docker push enriquemomice/multi-nginx
    - docker push enriquemomice/multi-server
    - docker push enriquemomice/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-917650463451
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY